services:
  taskmate_postgres:
    image: postgres:15
    restart: always
    environment:
      POSTGRES_DB: TaskMate
      POSTGRES_USER: bas
      POSTGRES_PASSWORD: password
    ports:
      - "2103:5432"
    volumes:
      - pg_data:/var/lib/postgresql/data

volumes:
  pg_data:
